import test from 'node:test';
import assert from 'node:assert/strict';
import { webcrypto, createHash } from 'node:crypto';
import { MAX_BYTES, parseExpectedHash, hashBytes, fingerprintFile } from '../../src/SchachTurnierManager.WebApp/public/backup-fingerprint/core.mjs';
const encode = text => new TextEncoder().encode(text);
const file = bytes => ({ size: bytes.length, arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) });
const abc = 'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad';
for (const value of ['', ' ', '\t\r\n']) test(`empty expected ${JSON.stringify(value)}`, () => assert.equal(parseExpectedHash(value), null));
for (const value of [abc, abc.toUpperCase(), '  '+abc+'\n']) test(`normalize valid ${JSON.stringify(value)}`, () => assert.equal(parseExpectedHash(value), abc));
for (const value of [null, 32, {}, 'a'.repeat(63), 'a'.repeat(65), 'z'.repeat(64), 'sha256:'+abc, abc+' file.json', abc.slice(0,32)+' '+abc.slice(32), '\uff41'.repeat(64)]) test(`invalid expected ${JSON.stringify(value)}`, () => assert.throws(() => parseExpectedHash(value), /INVALID_HASH/));
for (const text of ['', 'abc', 'Synthetic \u00dc\u00f1\u4e2d\ud83d\ude00', '\0\r\n', '\ufeff{}']) test(`hash matches independent node implementation ${JSON.stringify(text)}`, async () => assert.equal(await hashBytes(encode(text), webcrypto.subtle), createHash('sha256').update(encode(text)).digest('hex')));
test('known SHA-256 abc vector', async () => assert.equal(await hashBytes(encode('abc')), abc));
test('correct subarray only is hashed', async () => assert.equal(await hashBytes(encode('xabcx').subarray(1,4)), abc));
test('maximum size is accepted', async () => assert.equal((await hashBytes(new Uint8Array(MAX_BYTES))).length,64));
test('oversize rejected before crypto invocation', async () => { let calls=0; await assert.rejects(hashBytes(new Uint8Array(MAX_BYTES+1),{digest(){calls++;}}),/TOO_LARGE/); assert.equal(calls,0); });
test('invalid byte input rejected', async () => { await assert.rejects(hashBytes('abc'),/INVALID_BYTES/); });
test('missing web crypto reported explicitly', async () => { await assert.rejects(hashBytes(encode('abc'),null),/CRYPTO_UNAVAILABLE/); });
test('cryptographic error not replaced by success', async () => { await assert.rejects(hashBytes(encode('abc'),{digest:async()=>{throw Error('crypto failure');}}),/crypto failure/); });
test('input bytes not mutated', async () => { const bytes=encode('abc'), copy=bytes.slice(); await hashBytes(bytes); assert.deepEqual(bytes,copy); });
for (const [expected,comparison] of [['','NOT_REQUESTED'],[abc,'MATCH'],[abc.toUpperCase(),'MATCH'],['0'.repeat(64),'MISMATCH']]) test(`comparison ${comparison} ${expected.slice(0,2)}`, async () => { const r=await fingerprintFile(file(encode('abc')),expected); assert.equal(r.hash,abc); assert.equal(r.comparison,comparison); assert.equal(r.bytes,3); });
test('invalid expected hash prevents file read',async()=>{let calls=0;await assert.rejects(fingerprintFile({size:1,arrayBuffer:async()=>{calls++;return new ArrayBuffer(1);}},'bad'),/INVALID_HASH/);assert.equal(calls,0);});
test('oversized file prevents file read',async()=>{let calls=0;await assert.rejects(fingerprintFile({size:MAX_BYTES+1,arrayBuffer:async()=>{calls++;}}),/TOO_LARGE/);assert.equal(calls,0);});
for(const f of [null,{}, {size:-1}, {size:1.5},{size:NaN}]) test('missing/invalid file '+JSON.stringify(f),async()=>{await assert.rejects(fingerprintFile(f),/FILE_REQUIRED/);});
test('file read error is propagated',async()=>{await assert.rejects(fingerprintFile({size:1,arrayBuffer:async()=>{throw Error('read failure');}}),/read failure/);});
test('file size drift rejected',async()=>{await assert.rejects(fingerprintFile({size:4,arrayBuffer:async()=>encode('abc').buffer}),/FILE_CHANGED/);});
test('checksum is of bytes not JSON semantics',async()=>{assert.notEqual(await hashBytes(encode('{}')),await hashBytes(encode('{ }')));});
