import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { installConnectionCheck } from '../../src/SchachTurnierManager.WebApp/public/connection-check/app.js';
import { dom, deferred, browser } from './ui-harness.mjs';
const ids=['start','cancel','status','hint'];
const setup=(check=async()=>({status:'REACHABLE'}))=>{const d=dom(ids),w=browser();const dispose=installConnectionCheck(d,w,check);return {e:d.elements,w,dispose};};
test('opening or network-status events never send health requests',()=>{let calls=0;const {w}=setup(()=>calls++);w.fire('online');w.fire('offline');assert.equal(calls,0);});
test('offline hint is not mistaken for backend failure',()=>{const {e,w}=setup();w.navigator.onLine=false;w.fire('offline');assert.match(e.hint.textContent,/beweist nicht/);});
test('online status is not treated as API health',()=>{const {e}=setup();assert.match(e.hint.textContent,/kein Nachweis/);});
for(const status of ['REACHABLE','TIMEOUT','HTTP_ERROR','UNEXPECTED_REPLY','NETWORK_ERROR','CANCELLED'])test('actionable result '+status,async()=>{const {e}=setup(async()=>({status}));await e.start.fire('click');assert.equal(e.start.disabled,false);assert.equal(e.cancel.disabled,true);assert.notEqual(e.status.textContent,'');});
test('double-click creates a single request',async()=>{let calls=0;const wait=deferred();const {e}=setup(()=>{calls++;return wait.promise;});const p=e.start.fire('click');await e.start.fire('click');assert.equal(calls,1);wait.resolve({status:'REACHABLE'});await p;});
test('cancel aborts request and suppresses late success',async()=>{const wait=deferred();let signal;const {e}=setup(o=>{signal=o.signal;return wait.promise;});const p=e.start.fire('click');e.cancel.fire('click');wait.resolve({status:'REACHABLE'});await p;assert.equal(signal.aborted,true);assert.match(e.status.textContent,/abgebrochen/);});
test('new check survives late previous failure',async()=>{const wait=deferred();let calls=0;const {e}=setup(()=>++calls===1?wait.promise:Promise.resolve({status:'REACHABLE'}));const old=e.start.fire('click');e.cancel.fire('click');await e.start.fire('click');wait.reject(Error('PRIVATE'));await old;assert.match(e.status.textContent,/Healthantwort wurde empfangen/);});
test('raw errors and paths not rendered',async()=>{const {e}=setup(async()=>{throw Error('PRIVATE-path');});await e.start.fire('click');assert.equal(e.status.textContent.includes('PRIVATE'),false);});
test('unknown result code uses fixed neutral text',async()=>{const {e}=setup(async()=>({status:'__proto__'}));await e.start.fire('click');assert.equal(e.status.textContent.includes('[object'),false);});
test('disposal cancels operation and removes handlers',()=>{const {e,w,dispose}=setup();dispose();assert.equal(w.listeners.size,0);for(const id of ids)assert.equal(e[id].listeners.size,0);});
const html=readFileSync(new URL('../../src/SchachTurnierManager.WebApp/public/connection-check/index.html',import.meta.url),'utf8');
test('all IDs exist once and status is accessible',()=>{for(const id of ids)assert.equal(html.split(`id="${id}"`).length-1,1);assert.match(html,/aria-live="polite"/);});
test('CSP limits connection to same origin',()=>assert.ok(html.includes("connect-src 'self'")));
