import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { installFideSearch } from '../../src/SchachTurnierManager.WebApp/public/fide-search/app.js';
import { dom, deferred } from './ui-harness.mjs';
const ids=['file','query','federation','start','cancel','clear','status','rows'];
const result={rows:10,matches:1,omitted:0,items:[{id:'9900001',name:'Synthetic <img>',federation:'GER',standardRating:1800,title:'IM',womanTitle:''}]};
const setup=(search=async()=>result)=>{const d=dom(ids);const dispose=installFideSearch(d,search);return {d,e:d.elements,dispose};};
test('opening page does not search or read any file',()=>{let calls=0;const {e}=setup(()=>{calls++;});assert.equal(calls,0);assert.equal(e.start.disabled,false);assert.equal(e.cancel.disabled,true);});
test('result is rendered as text not HTML',async()=>{const {e}=setup();await e.start.fire('click');assert.equal(e.rows.children.length,1);assert.equal(e.rows.children[0].children[1].textContent,'Synthetic <img>');assert.match(e.status.textContent,/Keine Spielerdaten/);});
test('omitted result count is visible',async()=>{const {e}=setup(async()=>({...result,matches:70,omitted:69}));await e.start.fire('click');assert.match(e.status.textContent,/69 weitere/);});
test('double-click does not start duplicate search',async()=>{const wait=deferred();let calls=0;const {e}=setup(()=>{calls++;return wait.promise;});const run=e.start.fire('click');await e.start.fire('click');assert.equal(calls,1);wait.resolve(result);await run;assert.equal(e.start.disabled,false);});
for(const [id,event] of [['file','change'],['query','input'],['federation','input'],['clear','click'],['cancel','click']])test('invalidate pending result '+id,async()=>{const wait=deferred();let signal;const {e}=setup((_f,_q,_fed,o)=>{signal=o.signal;return wait.promise;});const run=e.start.fire('click');e[id].fire(event);wait.resolve(result);await run;assert.equal(signal.aborted,true);assert.equal(e.rows.children.length,0);});
test('late progress after cancellation does not overwrite status',async()=>{const wait=deferred();let progress;const {e}=setup((_f,_q,_fed,o)=>{progress=o.onProgress;return wait.promise;});const run=e.start.fire('click');e.cancel.fire('click');const status=e.status.textContent;progress({rows:900});assert.equal(e.status.textContent,status);wait.resolve(result);await run;});
test('late failure cannot overwrite newer search',async()=>{const wait=deferred();let calls=0;const {e}=setup(()=>++calls===1?wait.promise:Promise.resolve(result));const first=e.start.fire('click');e.query.fire('input');await e.start.fire('click');wait.reject(Error('PRIVATE'));await first;assert.equal(e.rows.children.length,1);});
test('raw errors never appear',async()=>{const {e}=setup(async()=>{throw Error('PRIVATE FILE');});await e.start.fire('click');assert.equal(e.status.textContent.includes('PRIVATE'),false);assert.equal(e.rows.children.length,0);});
test('disposing removes all event handlers and invalidates work',()=>{const {e,dispose}=setup();dispose();for(const id of ids)assert.equal(e[id].listeners.size,0);});
test('known error appears as actionable message',async()=>{const {e}=setup(async()=>{throw {code:'UNSUPPORTED_HEADER'};});await e.start.fire('click');assert.match(e.status.textContent,/TXT-Kopf/);});
const html=readFileSync(new URL('../../src/SchachTurnierManager.WebApp/public/fide-search/index.html',import.meta.url),'utf8');
test('all controller ids exist exactly once',()=>{for(const id of ids)assert.equal(html.split(`id="${id}"`).length-1,1);});
test('page denies network connections and has live status',()=>{assert.ok(html.includes("connect-src 'none'"));assert.match(html,/aria-live="polite"/);});
