import test from 'node:test';
import assert from 'node:assert/strict';
import { MAX_FILE_BYTES, prepareQuery, readHeader, readPlayer, searchRatingFile } from '../../src/SchachTurnierManager.WebApp/public/fide-search/core.js';
const layout = [['ID Number',12],['Name',36],['Fed',4],['Tit',5],['WTit',5],['SRtng',6],['Flag',4]];
const fixed = values => layout.map(([key,width]) => { const value = String(values[key] ?? ''); return value + ' '.repeat(Math.max(0, width - Array.from(value).length)); }).join('');
const header = fixed(Object.fromEntries(layout.map(([key]) => [key,key])));
const row = (id = '9900001', name = 'Synthetic Alpha', fed = 'GER', rating = '1800') => fixed({'ID Number':id,Name:name,Fed:fed,SRtng:rating,Tit:'m'});
const body = (rows = [row()], newline = '\n') => [header,...rows].join(newline);
const file = text => new Blob([text]);
const search = (text, query = 'Synthetic', fed = '', options) => searchRatingFile(file(text),query,fed,options);
const code = expected => failure => failure.code === expected;
for (const [name, fed] of [['ab',''],['Synthetic Alpha','GER'],['9900001',''],['\u00c1lpha',' ger ']]) test('valid query '+name,()=>assert.doesNotThrow(()=>prepareQuery(name,fed)));
for (const name of ['', 'a', ' ', 'x'.repeat(101), null, 'a b c d e f g h i']) test('invalid query '+JSON.stringify(name),()=>assert.throws(()=>prepareQuery(name),code('INVALID_QUERY')));
for (const fed of ['GE','GERM','G1R',null]) test('invalid federation '+fed,()=>assert.throws(()=>prepareQuery('Alpha',fed)));
for (const limit of [0,101,-1,1.5]) test('invalid limit '+limit,()=>assert.throws(()=>prepareQuery('Alpha','',limit),code('INVALID_LIMIT')));
test('correct fixed-width name federation title and standard rating',()=>assert.deepEqual(readPlayer(row(),readHeader(header)),{id:'9900001',name:'Synthetic Alpha',federation:'GER',standardRating:1800,title:'IM',womanTitle:''}));
test('no rating is not invented as an Elo',()=>assert.equal(readPlayer(row('9900001','Synthetic','GER','0'),readHeader(header)).standardRating,null));
test('unknown columns remain boundaries, not player data',()=>{ const h=header.replace('Flag','Note');assert.equal(readPlayer(row(),readHeader(h)).name,'Synthetic Alpha');});
for (const bad of ['<xml/>','ID Number Name Fed RRtng Flag',header.replace('SRtng','Rtg  '),header.replace('Fed','Name'),'\t'+header]) test('unsupported header '+bad.slice(0,30),()=>assert.throws(()=>readHeader(bad),code('UNSUPPORTED_HEADER')));
for (const bad of [row('0'),row('bad'),row('9900001','','GER'),row('9900001','A','xx'),row('9900001','A','GER','4001'),row('9900001','A','GER','-1'),row().slice(0,20),row().replace('Alpha','A\0pha')]) test('invalid row '+JSON.stringify(bad.slice(0,24)),()=>assert.throws(()=>readPlayer(bad,readHeader(header)),code('INVALID_ROW')));
test('name tokens are accent-insensitive and order-independent',async()=>{const r=await search(body([row('9900001','Synthetic, \u00c1lpha'),row('9900002','Synthetic Beta')]),'alpha synthetic');assert.equal(r.matches,1);assert.equal(r.items[0].id,'9900001');});
test('FIDE ID exact match',async()=>{const r=await search(body([row('9900001'),row('99000012')]),'9900001');assert.equal(r.matches,1);});
test('federation filter',async()=>{const r=await search(body([row(),row('9900002','Synthetic Beta','ESP')]),'synthetic',' esp ');assert.equal(r.matches,1);assert.equal(r.items[0].federation,'ESP');});
test('zero matches is a complete result',async()=>{const r=await search(body(),'Absent');assert.equal(r.rows,1);assert.equal(r.matches,0);assert.deepEqual(r.items,[]);});
test('result cap preserves true total and file order',async()=>{const r=await search(body([row('9900001'),row('9900002'),row('9900003')]),'Synthetic','',{limit:1});assert.equal(r.matches,3);assert.equal(r.omitted,2);assert.equal(r.items[0].id,'9900001');});
for(const newline of ['\n','\r\n'])test('line endings '+JSON.stringify(newline),async()=>assert.equal((await search('\ufeff'+body([row()],newline)+newline)).matches,1));
test('small chunks split UTF-8 and lines safely',async()=>{const bytes=new TextEncoder().encode(body([row('9900001','Synthetic \u00dc')],'\r\n'));let i=0;const f={size:bytes.length,stream:()=>new ReadableStream({pull(c){if(i===bytes.length)c.close();else c.enqueue(bytes.slice(i,i+=1));}})};assert.equal((await searchRatingFile(f,'synthetic')).items[0].name,'Synthetic \u00dc');});
test('invalid later record discards any earlier matches',async()=>await assert.rejects(search(body([row(),'corrupt'])),code('INVALID_ROW')));
test('empty list rejected',async()=>await assert.rejects(search(header),code('EMPTY_LIST')));
test('invalid UTF-8 rejected without leaking decoder error',async()=>await assert.rejects(searchRatingFile(new Blob([new Uint8Array([255])]),'Alpha'),code('FILE_READ_ERROR')));
test('metadata mismatch rejected',async()=>{const f=file(body());await assert.rejects(searchRatingFile({size:f.size+1,stream:()=>f.stream()},'Alpha'),code('FILE_CHANGED'));});
test('oversized input rejected before open',async()=>{let opens=0;await assert.rejects(searchRatingFile({size:MAX_FILE_BYTES+1,stream(){opens++;}},'Alpha'),code('INVALID_FILE'));assert.equal(opens,0);});
test('pre-cancelled search never reads file',async()=>{const c=new AbortController();c.abort();await assert.rejects(search(body(),'Alpha','',{signal:c.signal}),code('CANCELLED'));});
test('progress and cancellation work during a large scan',async()=>{const c=new AbortController();let calls=0;const rows=Array.from({length:2500},(_,i)=>row(String(9900000+i)));await assert.rejects(search(body(rows),'Synthetic','',{signal:c.signal,onProgress(){calls++;c.abort();}}),code('CANCELLED'));assert.equal(calls,1);});
test('cancel also interrupts a blocked stream read',async()=>{const c=new AbortController();let cancelled=false;const f={size:1,stream:()=>new ReadableStream({cancel(){cancelled=true;}})};const work=searchRatingFile(f,'Alpha','',{signal:c.signal});c.abort();await assert.rejects(work,code('CANCELLED'));assert.equal(cancelled,true);});
test('ten thousand rows scanned without retaining every player',async()=>{const r=await search(body(Array.from({length:10000},(_,i)=>row(String(9900000+i)))));assert.equal(r.rows,10000);assert.equal(r.items.length,50);assert.equal(r.omitted,9950);});
test('repeat results are deterministic',async()=>{const text=body([row(),row('9900002')]);assert.deepEqual(await search(text),await search(text));});
