import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { installSupportSummary } from '../../src/SchachTurnierManager.WebApp/public/support-summary/app.js';
import { dom, deferred } from './ui-harness.mjs';
const ids=['file','start','clear','status','output','result'];
const summary={schema:'stm-support-counts-1',counts:{players:2}};
const setup=(compute=async()=>summary)=>{const d=dom(ids);const dispose=installSupportSummary(d,compute);return {d,e:d.elements,dispose};};
test('opening page performs no file read',()=>{let calls=0;setup(()=>calls++);assert.equal(calls,0);});
test('real file and projection run through the UI',async()=>{const d=dom(ids);installSupportSummary(d);d.elements.file.files=[new Blob([JSON.stringify({id:'PRIVATE',name:'PRIVATE',settings:{},players:[],rounds:[]})])];await d.elements.start.fire('click');const report=JSON.parse(d.elements.output.value);assert.equal(report.counts.players,0);assert.equal(d.elements.output.value.includes('PRIVATE'),false);});
test('success is a manual-copy preview with privacy caveat',async()=>{const {e}=setup();await e.start.fire('click');assert.equal(e.result.hidden,false);assert.deepEqual(JSON.parse(e.output.value),summary);assert.match(e.status.textContent,/vertraulich/);});
test('double-click is ignored while pending',async()=>{const wait=deferred();let calls=0;const {e}=setup(()=>{calls++;return wait.promise;});const p=e.start.fire('click');await e.start.fire('click');assert.equal(calls,1);wait.resolve(summary);await p;});
for(const [id,event] of [['file','change'],['clear','click']])test('selection invalidation '+id,async()=>{const wait=deferred();const {e}=setup(()=>wait.promise);const run=e.start.fire('click');e[id].fire(event);wait.resolve(summary);await run;assert.equal(e.result.hidden,true);assert.equal(e.output.value,'');});
test('newer result wins over an old rejected read',async()=>{let calls=0;const wait=deferred();const {e}=setup(()=>++calls===1?wait.promise:Promise.resolve(summary));const old=e.start.fire('click');e.file.fire('change');await e.start.fire('click');wait.reject(Error('SECRET'));await old;assert.equal(e.result.hidden,false);assert.equal(e.status.textContent.includes('SECRET'),false);});
test('error clears previous report',async()=>{let calls=0;const {e}=setup(async()=>{if(++calls===1)return summary;throw Error('PRIVATE');});await e.start.fire('click');await e.start.fire('click');assert.equal(e.result.hidden,true);assert.equal(e.output.value,'');assert.equal(e.status.textContent.includes('PRIVATE'),false);});
test('prototype-like error is not displayed',async()=>{const {e}=setup(async()=>{throw {code:'constructor'};});await e.start.fire('click');assert.equal(e.status.textContent.includes('function'),false);});
test('dispose removes handlers and suppresses output',async()=>{const wait=deferred();const {e,dispose}=setup(()=>wait.promise);const p=e.start.fire('click');dispose();wait.resolve(summary);await p;assert.equal(e.result.hidden,true);for(const id of ids)assert.equal(e[id].listeners.size,0);});
const html=readFileSync(new URL('../../src/SchachTurnierManager.WebApp/public/support-summary/index.html',import.meta.url),'utf8');
test('all controller IDs appear once',()=>{for(const id of ids)assert.equal(html.split(`id="${id}"`).length-1,1);});
test('no upload or form submission allowed and output is readonly',()=>{assert.ok(html.includes("connect-src 'none'"));assert.ok(html.includes("form-action 'none'"));assert.match(html,/<textarea[^>]+readonly/);});
